/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.9.1.119 */
/* Module Version: 5.8 */
/* /usr/local/diamond/3.9_x64/ispfpga/bin/lin64/scuba -w -n fifo_buffer -lang verilog -synth synplify -bus_exp 7 -bb -arch xo2c00 -type ebfifo -depth 4096 -width 32 -rwidth 32 -no_enable -pe 128 -pf 4088  */
/* Sat Jul 21 19:48:17 2018 */


`timescale 1 ns / 1 ps
module fifo_buffer (Data, WrClock, RdClock, WrEn, RdEn, Reset, RPReset, 
    Q, Empty, Full, AlmostEmpty, AlmostFull)/* synthesis NGD_DRC_MASK=1 */;
    input wire [31:0] Data;
    input wire WrClock;
    input wire RdClock;
    input wire WrEn;
    input wire RdEn;
    input wire Reset;
    input wire RPReset;
    output wire [31:0] Q;
    output wire Empty;
    output wire Full;
    output wire AlmostEmpty;
    output wire AlmostFull;

    wire scuba_vhi;
    wire Empty_int;
    wire Full_int;
    wire scuba_vlo;

    defparam fifo_buffer_0_15.FULLPOINTER1 = "0b01111111111110" ;
    defparam fifo_buffer_0_15.FULLPOINTER = "0b10000000000000" ;
    defparam fifo_buffer_0_15.AFPOINTER1 = "0b01111111101110" ;
    defparam fifo_buffer_0_15.AFPOINTER = "0b01111111110000" ;
    defparam fifo_buffer_0_15.AEPOINTER1 = "0b00000100000010" ;
    defparam fifo_buffer_0_15.AEPOINTER = "0b00000100000000" ;
    defparam fifo_buffer_0_15.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_buffer_0_15.GSR = "DISABLED" ;
    defparam fifo_buffer_0_15.RESETMODE = "ASYNC" ;
    defparam fifo_buffer_0_15.REGMODE = "NOREG" ;
    defparam fifo_buffer_0_15.CSDECODE_R = "0b11" ;
    defparam fifo_buffer_0_15.CSDECODE_W = "0b11" ;
    defparam fifo_buffer_0_15.DATA_WIDTH_R = 2 ;
    defparam fifo_buffer_0_15.DATA_WIDTH_W = 2 ;
    FIFO8KB fifo_buffer_0_15 (.DI0(scuba_vlo), .DI1(scuba_vlo), .DI2(Data[0]), 
        .DI3(scuba_vlo), .DI4(scuba_vlo), .DI5(Data[1]), .DI6(scuba_vlo), 
        .DI7(scuba_vlo), .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), 
        .DI11(Data[0]), .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), 
        .DI15(scuba_vlo), .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[0]), .DO1(Q[1]), 
        .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), 
        .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), 
        .EF(Empty_int), .AEF(AlmostEmpty), .AFF(AlmostFull), .FF(Full_int));

    defparam fifo_buffer_1_14.FULLPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_1_14.FULLPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_1_14.AFPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_1_14.AFPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_1_14.AEPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_1_14.AEPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_1_14.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_buffer_1_14.GSR = "DISABLED" ;
    defparam fifo_buffer_1_14.RESETMODE = "ASYNC" ;
    defparam fifo_buffer_1_14.REGMODE = "NOREG" ;
    defparam fifo_buffer_1_14.CSDECODE_R = "0b11" ;
    defparam fifo_buffer_1_14.CSDECODE_W = "0b11" ;
    defparam fifo_buffer_1_14.DATA_WIDTH_R = 2 ;
    defparam fifo_buffer_1_14.DATA_WIDTH_W = 2 ;
    FIFO8KB fifo_buffer_1_14 (.DI0(scuba_vlo), .DI1(scuba_vlo), .DI2(Data[2]), 
        .DI3(scuba_vlo), .DI4(scuba_vlo), .DI5(Data[3]), .DI6(scuba_vlo), 
        .DI7(scuba_vlo), .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), 
        .DI11(Data[2]), .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), 
        .DI15(scuba_vlo), .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[2]), .DO1(Q[3]), 
        .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), 
        .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), 
        .EF(), .AEF(), .AFF(), .FF());

    defparam fifo_buffer_2_13.FULLPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_2_13.FULLPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_2_13.AFPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_2_13.AFPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_2_13.AEPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_2_13.AEPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_2_13.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_buffer_2_13.GSR = "DISABLED" ;
    defparam fifo_buffer_2_13.RESETMODE = "ASYNC" ;
    defparam fifo_buffer_2_13.REGMODE = "NOREG" ;
    defparam fifo_buffer_2_13.CSDECODE_R = "0b11" ;
    defparam fifo_buffer_2_13.CSDECODE_W = "0b11" ;
    defparam fifo_buffer_2_13.DATA_WIDTH_R = 2 ;
    defparam fifo_buffer_2_13.DATA_WIDTH_W = 2 ;
    FIFO8KB fifo_buffer_2_13 (.DI0(scuba_vlo), .DI1(scuba_vlo), .DI2(Data[4]), 
        .DI3(scuba_vlo), .DI4(scuba_vlo), .DI5(Data[5]), .DI6(scuba_vlo), 
        .DI7(scuba_vlo), .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), 
        .DI11(Data[4]), .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), 
        .DI15(scuba_vlo), .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[4]), .DO1(Q[5]), 
        .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), 
        .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), 
        .EF(), .AEF(), .AFF(), .FF());

    defparam fifo_buffer_3_12.FULLPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_3_12.FULLPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_3_12.AFPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_3_12.AFPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_3_12.AEPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_3_12.AEPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_3_12.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_buffer_3_12.GSR = "DISABLED" ;
    defparam fifo_buffer_3_12.RESETMODE = "ASYNC" ;
    defparam fifo_buffer_3_12.REGMODE = "NOREG" ;
    defparam fifo_buffer_3_12.CSDECODE_R = "0b11" ;
    defparam fifo_buffer_3_12.CSDECODE_W = "0b11" ;
    defparam fifo_buffer_3_12.DATA_WIDTH_R = 2 ;
    defparam fifo_buffer_3_12.DATA_WIDTH_W = 2 ;
    FIFO8KB fifo_buffer_3_12 (.DI0(scuba_vlo), .DI1(scuba_vlo), .DI2(Data[6]), 
        .DI3(scuba_vlo), .DI4(scuba_vlo), .DI5(Data[7]), .DI6(scuba_vlo), 
        .DI7(scuba_vlo), .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), 
        .DI11(Data[6]), .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), 
        .DI15(scuba_vlo), .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[6]), .DO1(Q[7]), 
        .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), 
        .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), 
        .EF(), .AEF(), .AFF(), .FF());

    defparam fifo_buffer_4_11.FULLPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_4_11.FULLPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_4_11.AFPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_4_11.AFPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_4_11.AEPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_4_11.AEPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_4_11.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_buffer_4_11.GSR = "DISABLED" ;
    defparam fifo_buffer_4_11.RESETMODE = "ASYNC" ;
    defparam fifo_buffer_4_11.REGMODE = "NOREG" ;
    defparam fifo_buffer_4_11.CSDECODE_R = "0b11" ;
    defparam fifo_buffer_4_11.CSDECODE_W = "0b11" ;
    defparam fifo_buffer_4_11.DATA_WIDTH_R = 2 ;
    defparam fifo_buffer_4_11.DATA_WIDTH_W = 2 ;
    FIFO8KB fifo_buffer_4_11 (.DI0(scuba_vlo), .DI1(scuba_vlo), .DI2(Data[8]), 
        .DI3(scuba_vlo), .DI4(scuba_vlo), .DI5(Data[9]), .DI6(scuba_vlo), 
        .DI7(scuba_vlo), .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), 
        .DI11(Data[8]), .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), 
        .DI15(scuba_vlo), .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[8]), .DO1(Q[9]), 
        .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), 
        .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), 
        .EF(), .AEF(), .AFF(), .FF());

    defparam fifo_buffer_5_10.FULLPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_5_10.FULLPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_5_10.AFPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_5_10.AFPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_5_10.AEPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_5_10.AEPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_5_10.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_buffer_5_10.GSR = "DISABLED" ;
    defparam fifo_buffer_5_10.RESETMODE = "ASYNC" ;
    defparam fifo_buffer_5_10.REGMODE = "NOREG" ;
    defparam fifo_buffer_5_10.CSDECODE_R = "0b11" ;
    defparam fifo_buffer_5_10.CSDECODE_W = "0b11" ;
    defparam fifo_buffer_5_10.DATA_WIDTH_R = 2 ;
    defparam fifo_buffer_5_10.DATA_WIDTH_W = 2 ;
    FIFO8KB fifo_buffer_5_10 (.DI0(scuba_vlo), .DI1(scuba_vlo), .DI2(Data[10]), 
        .DI3(scuba_vlo), .DI4(scuba_vlo), .DI5(Data[11]), .DI6(scuba_vlo), 
        .DI7(scuba_vlo), .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), 
        .DI11(Data[10]), .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), 
        .DI15(scuba_vlo), .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[10]), .DO1(Q[11]), 
        .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), 
        .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), 
        .EF(), .AEF(), .AFF(), .FF());

    defparam fifo_buffer_6_9.FULLPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_6_9.FULLPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_6_9.AFPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_6_9.AFPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_6_9.AEPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_6_9.AEPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_6_9.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_buffer_6_9.GSR = "DISABLED" ;
    defparam fifo_buffer_6_9.RESETMODE = "ASYNC" ;
    defparam fifo_buffer_6_9.REGMODE = "NOREG" ;
    defparam fifo_buffer_6_9.CSDECODE_R = "0b11" ;
    defparam fifo_buffer_6_9.CSDECODE_W = "0b11" ;
    defparam fifo_buffer_6_9.DATA_WIDTH_R = 2 ;
    defparam fifo_buffer_6_9.DATA_WIDTH_W = 2 ;
    FIFO8KB fifo_buffer_6_9 (.DI0(scuba_vlo), .DI1(scuba_vlo), .DI2(Data[12]), 
        .DI3(scuba_vlo), .DI4(scuba_vlo), .DI5(Data[13]), .DI6(scuba_vlo), 
        .DI7(scuba_vlo), .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), 
        .DI11(Data[12]), .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), 
        .DI15(scuba_vlo), .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[12]), .DO1(Q[13]), 
        .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), 
        .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), 
        .EF(), .AEF(), .AFF(), .FF());

    defparam fifo_buffer_7_8.FULLPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_7_8.FULLPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_7_8.AFPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_7_8.AFPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_7_8.AEPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_7_8.AEPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_7_8.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_buffer_7_8.GSR = "DISABLED" ;
    defparam fifo_buffer_7_8.RESETMODE = "ASYNC" ;
    defparam fifo_buffer_7_8.REGMODE = "NOREG" ;
    defparam fifo_buffer_7_8.CSDECODE_R = "0b11" ;
    defparam fifo_buffer_7_8.CSDECODE_W = "0b11" ;
    defparam fifo_buffer_7_8.DATA_WIDTH_R = 2 ;
    defparam fifo_buffer_7_8.DATA_WIDTH_W = 2 ;
    FIFO8KB fifo_buffer_7_8 (.DI0(scuba_vlo), .DI1(scuba_vlo), .DI2(Data[14]), 
        .DI3(scuba_vlo), .DI4(scuba_vlo), .DI5(Data[15]), .DI6(scuba_vlo), 
        .DI7(scuba_vlo), .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), 
        .DI11(Data[14]), .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), 
        .DI15(scuba_vlo), .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[14]), .DO1(Q[15]), 
        .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), 
        .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), 
        .EF(), .AEF(), .AFF(), .FF());

    defparam fifo_buffer_8_7.FULLPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_8_7.FULLPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_8_7.AFPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_8_7.AFPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_8_7.AEPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_8_7.AEPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_8_7.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_buffer_8_7.GSR = "DISABLED" ;
    defparam fifo_buffer_8_7.RESETMODE = "ASYNC" ;
    defparam fifo_buffer_8_7.REGMODE = "NOREG" ;
    defparam fifo_buffer_8_7.CSDECODE_R = "0b11" ;
    defparam fifo_buffer_8_7.CSDECODE_W = "0b11" ;
    defparam fifo_buffer_8_7.DATA_WIDTH_R = 2 ;
    defparam fifo_buffer_8_7.DATA_WIDTH_W = 2 ;
    FIFO8KB fifo_buffer_8_7 (.DI0(scuba_vlo), .DI1(scuba_vlo), .DI2(Data[16]), 
        .DI3(scuba_vlo), .DI4(scuba_vlo), .DI5(Data[17]), .DI6(scuba_vlo), 
        .DI7(scuba_vlo), .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), 
        .DI11(Data[16]), .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), 
        .DI15(scuba_vlo), .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[16]), .DO1(Q[17]), 
        .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), 
        .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), 
        .EF(), .AEF(), .AFF(), .FF());

    defparam fifo_buffer_9_6.FULLPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_9_6.FULLPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_9_6.AFPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_9_6.AFPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_9_6.AEPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_9_6.AEPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_9_6.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_buffer_9_6.GSR = "DISABLED" ;
    defparam fifo_buffer_9_6.RESETMODE = "ASYNC" ;
    defparam fifo_buffer_9_6.REGMODE = "NOREG" ;
    defparam fifo_buffer_9_6.CSDECODE_R = "0b11" ;
    defparam fifo_buffer_9_6.CSDECODE_W = "0b11" ;
    defparam fifo_buffer_9_6.DATA_WIDTH_R = 2 ;
    defparam fifo_buffer_9_6.DATA_WIDTH_W = 2 ;
    FIFO8KB fifo_buffer_9_6 (.DI0(scuba_vlo), .DI1(scuba_vlo), .DI2(Data[18]), 
        .DI3(scuba_vlo), .DI4(scuba_vlo), .DI5(Data[19]), .DI6(scuba_vlo), 
        .DI7(scuba_vlo), .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), 
        .DI11(Data[18]), .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), 
        .DI15(scuba_vlo), .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[18]), .DO1(Q[19]), 
        .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), 
        .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), 
        .EF(), .AEF(), .AFF(), .FF());

    defparam fifo_buffer_10_5.FULLPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_10_5.FULLPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_10_5.AFPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_10_5.AFPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_10_5.AEPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_10_5.AEPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_10_5.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_buffer_10_5.GSR = "DISABLED" ;
    defparam fifo_buffer_10_5.RESETMODE = "ASYNC" ;
    defparam fifo_buffer_10_5.REGMODE = "NOREG" ;
    defparam fifo_buffer_10_5.CSDECODE_R = "0b11" ;
    defparam fifo_buffer_10_5.CSDECODE_W = "0b11" ;
    defparam fifo_buffer_10_5.DATA_WIDTH_R = 2 ;
    defparam fifo_buffer_10_5.DATA_WIDTH_W = 2 ;
    FIFO8KB fifo_buffer_10_5 (.DI0(scuba_vlo), .DI1(scuba_vlo), .DI2(Data[20]), 
        .DI3(scuba_vlo), .DI4(scuba_vlo), .DI5(Data[21]), .DI6(scuba_vlo), 
        .DI7(scuba_vlo), .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), 
        .DI11(Data[20]), .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), 
        .DI15(scuba_vlo), .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[20]), .DO1(Q[21]), 
        .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), 
        .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), 
        .EF(), .AEF(), .AFF(), .FF());

    defparam fifo_buffer_11_4.FULLPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_11_4.FULLPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_11_4.AFPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_11_4.AFPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_11_4.AEPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_11_4.AEPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_11_4.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_buffer_11_4.GSR = "DISABLED" ;
    defparam fifo_buffer_11_4.RESETMODE = "ASYNC" ;
    defparam fifo_buffer_11_4.REGMODE = "NOREG" ;
    defparam fifo_buffer_11_4.CSDECODE_R = "0b11" ;
    defparam fifo_buffer_11_4.CSDECODE_W = "0b11" ;
    defparam fifo_buffer_11_4.DATA_WIDTH_R = 2 ;
    defparam fifo_buffer_11_4.DATA_WIDTH_W = 2 ;
    FIFO8KB fifo_buffer_11_4 (.DI0(scuba_vlo), .DI1(scuba_vlo), .DI2(Data[22]), 
        .DI3(scuba_vlo), .DI4(scuba_vlo), .DI5(Data[23]), .DI6(scuba_vlo), 
        .DI7(scuba_vlo), .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), 
        .DI11(Data[22]), .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), 
        .DI15(scuba_vlo), .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[22]), .DO1(Q[23]), 
        .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), 
        .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), 
        .EF(), .AEF(), .AFF(), .FF());

    defparam fifo_buffer_12_3.FULLPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_12_3.FULLPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_12_3.AFPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_12_3.AFPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_12_3.AEPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_12_3.AEPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_12_3.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_buffer_12_3.GSR = "DISABLED" ;
    defparam fifo_buffer_12_3.RESETMODE = "ASYNC" ;
    defparam fifo_buffer_12_3.REGMODE = "NOREG" ;
    defparam fifo_buffer_12_3.CSDECODE_R = "0b11" ;
    defparam fifo_buffer_12_3.CSDECODE_W = "0b11" ;
    defparam fifo_buffer_12_3.DATA_WIDTH_R = 2 ;
    defparam fifo_buffer_12_3.DATA_WIDTH_W = 2 ;
    FIFO8KB fifo_buffer_12_3 (.DI0(scuba_vlo), .DI1(scuba_vlo), .DI2(Data[24]), 
        .DI3(scuba_vlo), .DI4(scuba_vlo), .DI5(Data[25]), .DI6(scuba_vlo), 
        .DI7(scuba_vlo), .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), 
        .DI11(Data[24]), .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), 
        .DI15(scuba_vlo), .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[24]), .DO1(Q[25]), 
        .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), 
        .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), 
        .EF(), .AEF(), .AFF(), .FF());

    defparam fifo_buffer_13_2.FULLPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_13_2.FULLPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_13_2.AFPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_13_2.AFPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_13_2.AEPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_13_2.AEPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_13_2.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_buffer_13_2.GSR = "DISABLED" ;
    defparam fifo_buffer_13_2.RESETMODE = "ASYNC" ;
    defparam fifo_buffer_13_2.REGMODE = "NOREG" ;
    defparam fifo_buffer_13_2.CSDECODE_R = "0b11" ;
    defparam fifo_buffer_13_2.CSDECODE_W = "0b11" ;
    defparam fifo_buffer_13_2.DATA_WIDTH_R = 2 ;
    defparam fifo_buffer_13_2.DATA_WIDTH_W = 2 ;
    FIFO8KB fifo_buffer_13_2 (.DI0(scuba_vlo), .DI1(scuba_vlo), .DI2(Data[26]), 
        .DI3(scuba_vlo), .DI4(scuba_vlo), .DI5(Data[27]), .DI6(scuba_vlo), 
        .DI7(scuba_vlo), .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), 
        .DI11(Data[26]), .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), 
        .DI15(scuba_vlo), .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[26]), .DO1(Q[27]), 
        .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), 
        .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), 
        .EF(), .AEF(), .AFF(), .FF());

    defparam fifo_buffer_14_1.FULLPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_14_1.FULLPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_14_1.AFPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_14_1.AFPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_14_1.AEPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_14_1.AEPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_14_1.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_buffer_14_1.GSR = "DISABLED" ;
    defparam fifo_buffer_14_1.RESETMODE = "ASYNC" ;
    defparam fifo_buffer_14_1.REGMODE = "NOREG" ;
    defparam fifo_buffer_14_1.CSDECODE_R = "0b11" ;
    defparam fifo_buffer_14_1.CSDECODE_W = "0b11" ;
    defparam fifo_buffer_14_1.DATA_WIDTH_R = 2 ;
    defparam fifo_buffer_14_1.DATA_WIDTH_W = 2 ;
    FIFO8KB fifo_buffer_14_1 (.DI0(scuba_vlo), .DI1(scuba_vlo), .DI2(Data[28]), 
        .DI3(scuba_vlo), .DI4(scuba_vlo), .DI5(Data[29]), .DI6(scuba_vlo), 
        .DI7(scuba_vlo), .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), 
        .DI11(Data[28]), .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), 
        .DI15(scuba_vlo), .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[28]), .DO1(Q[29]), 
        .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), 
        .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), 
        .EF(), .AEF(), .AFF(), .FF());

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam fifo_buffer_15_0.FULLPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_15_0.FULLPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_15_0.AFPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_15_0.AFPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_15_0.AEPOINTER1 = "0b00000000000000" ;
    defparam fifo_buffer_15_0.AEPOINTER = "0b11111111111110" ;
    defparam fifo_buffer_15_0.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_buffer_15_0.GSR = "DISABLED" ;
    defparam fifo_buffer_15_0.RESETMODE = "ASYNC" ;
    defparam fifo_buffer_15_0.REGMODE = "NOREG" ;
    defparam fifo_buffer_15_0.CSDECODE_R = "0b11" ;
    defparam fifo_buffer_15_0.CSDECODE_W = "0b11" ;
    defparam fifo_buffer_15_0.DATA_WIDTH_R = 2 ;
    defparam fifo_buffer_15_0.DATA_WIDTH_W = 2 ;
    FIFO8KB fifo_buffer_15_0 (.DI0(scuba_vlo), .DI1(scuba_vlo), .DI2(Data[30]), 
        .DI3(scuba_vlo), .DI4(scuba_vlo), .DI5(Data[31]), .DI6(scuba_vlo), 
        .DI7(scuba_vlo), .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), 
        .DI11(Data[30]), .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), 
        .DI15(scuba_vlo), .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), 
        .CSW1(scuba_vhi), .CSR0(scuba_vhi), .CSR1(scuba_vhi), .FULLI(Full_int), 
        .EMPTYI(Empty_int), .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), 
        .CLKR(RdClock), .RST(Reset), .RPRST(RPReset), .DO0(Q[30]), .DO1(Q[31]), 
        .DO2(), .DO3(), .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), 
        .DO10(), .DO11(), .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), 
        .EF(), .AEF(), .AFF(), .FF());

    assign Empty = Empty_int;
    assign Full = Full_int;


    // exemplar begin
    // exemplar end

endmodule
