/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.7.0.96.1 */
/* Module Version: 5.7 */
/* Wed Jun 14 21:59:36 2017 */

/* parameterized module instance */
pll __ (.CLKI( ), .CLKOP( ));
