/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.9.1.119 */
/* Module Version: 1.2 */
/* Sat Jun 17 18:26:17 2017 */

/* parameterized module instance */
pwr_cntrllr __ (.USERSTDBY( ), .CLRFLAG( ), .CFGSTDBY( ), .STDBY( ), 
    .SFLAG( ));
