/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.7.0.96.1 */
/* Module Version: 1.2 */
/* Wed Jun 14 21:17:46 2017 */

/* parameterized module instance */
pwr_cntrllr __ (.USERSTDBY( ), .CLRFLAG( ), .CFGSTDBY( ), .STDBY( ), 
    .SFLAG( ));
