/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.9.1.119 */
/* Module Version: 1.2 */
/* /usr/local/diamond/3.9_x64/ispfpga/bin/lin64/scuba -w -n pwr_cntrllr -lang verilog -synth synplify -bus_exp 7 -bb -arch xo2c00 -type power_cntl -entry USER_CFG -s2s BYPASS -wake USER -standby -por_off  */
/* Mon Jun  4 22:34:11 2018 */


`timescale 1 ns / 1 ps
module pwr_cntrllr (USERSTDBY, CLRFLAG, CFGSTDBY, STDBY, SFLAG)/* synthesis NGD_DRC_MASK=1 */;
    input wire USERSTDBY;
    input wire CLRFLAG;
    input wire CFGSTDBY;
    output wire STDBY;
    output wire SFLAG;

    wire scuba_vlo;

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam PCNTR_Inst0.BGOFF = "FALSE" ;
    defparam PCNTR_Inst0.POROFF = "TRUE" ;
    defparam PCNTR_Inst0.WAKEUP = "USER" ;
    defparam PCNTR_Inst0.TIMEOUT = "BYPASS" ;
    defparam PCNTR_Inst0.STDBYOPT = "USER_CFG" ;
    PCNTR PCNTR_Inst0 (.CLK(scuba_vlo), .USERTIMEOUT(scuba_vlo), .USERSTDBY(USERSTDBY), 
        .CLRFLAG(CLRFLAG), .CFGWAKE(scuba_vlo), .CFGSTDBY(CFGSTDBY), .STDBY(STDBY), 
        .STOP(), .SFLAG(SFLAG));



    // exemplar begin
    // exemplar end

endmodule
